name: Build-Deb

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Debian package
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Sparse checkout of debrepo (only nm-user-dispatcher/)
        run: |
          git init debrepo
          cd debrepo
          git remote add origin https://${{ secrets.DEBREPO_USERNAME }}:${{ secrets.DEBREPO_TOKEN }}@git.0xmax42.io/maxp/debrepo.git
          git config core.sparseCheckout true
          echo "nm-user-dispatcher/" >> .git/info/sparse-checkout
          git pull --depth=1 origin packages
          git checkout -b packages

      - name: Copy .deb + source files to debrepo nm-user-dispatcher directory
        run: |
          mkdir -p debrepo/nm-user-dispatcher
          cp ./dist/tux-hwmon*.deb debrepo/nm-user-dispatcher/ || true
          cp ./dist/tux-hwmon*.dsc debrepo/nm-user-dispatcher/ || true
          cp ./dist/tux-hwmon*.tar.* debrepo/nm-user-dispatcher/ || true

      - name: Commit and push package artifacts to debrepo
        working-directory: debrepo
        run: |
          set -euo pipefail
          git config user.name "$CI_COMMIT_AUTHOR_NAME"
          git config user.email "$CI_COMMIT_AUTHOR_EMAIL"

          # Alle neuen Artefakte hinzufügen (.deb, .dsc, .tar.*)
          for file in nm-user-dispatcher/tux-hwmon*.{deb,dsc,tar.gz,tar.xz}; do
            if [ -e "$file" ]; then
              if git ls-files --error-unmatch "$file" > /dev/null 2>&1; then
                echo "Datei $file ist bereits im Repository – überspringe."
              else
                echo "Neue Datei $file wird hinzugefügt."
                git add "$file"
              fi
            fi
          done

          git commit -m "Add nm-user-dispatcher package version ${{ steps.read_version.outputs.VERSION }}" || echo "No changes to commit"
          git push origin packages
