name: BATs tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yq bash bats make

      - name: Run BATs tests
        run: |
          make test
